exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


exec-once = swww-daemon

exec-once = swww img ~/.config/hypr/wallpapers/castlevania.jpg

exec-once = hypridle
# exec-once = waybar
# exec-once = ags
exec-once = hyprpanel
exec-once = easyeffects --gapplication-service
# exec-once = wl-paste -p -t text --watch clipman store -P --histpath="~/.local/share/clipman-primary.json"

exec-once = wl-clipboard-history -t   
exec-once = wl-paste --watch cliphist store    
exec-once = rm "$HOME/.cache/cliphist/db"   #it'll delete history at every restart   

exec-once = discord
exec-once = spotify