plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
}

source=~/.config/hypr/defaults/monitors.conf
source=~/.config/hypr/defaults/env.conf
source=~/.config/hypr/defaults/execs.conf
source=~/.config/hypr/defaults/general.conf
source=~/.config/hypr/defaults/rules.conf
source=~/.config/hypr/defaults/colors.conf
source=~/.config/hypr/defaults/keybinds.conf
